
server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://47.96.111.11:3306/db_wfx?characterEncoding=UTF-8&useSSl=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Xx520ff728116/.
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xc.xcmcs.pojo